hedgehogqa/fsharp-hedgehog

- build.sh
@moodmosaic would you mind checking if this new `build.sh` works as expected on Windows?
The general idea is that the bootstrapper is only run if it's been more than 24 hours since the last run. Would be nice to know if the `COMSPEC` trick works as well.
> Add marker file so the bootstrapper is only run every 24 hours

- build.sh
in order to make it clear that the build isn't always triggered via Mono.
> Make build.sh easier to maintain,

- Jack/Gen.fs
- Jack/Random.fs
I think we could almost get rid of Random altogether now, I only added it to simplify implementing bind for `Gen` but after some simplifications it's fairly straightforward.
> Implement Gen.bind directly instead of using promote

- Jack/Jack.fsproj
- Jack/Property.fs
- Jack/Script.fsx
If you run the first part of the `Script.fsx`:
```fs
// specialized computation expression 'forAll' which
// is like 'gen' but keeps track of bound arguments so
// they can be reported in counterexamples
Property.check <| forAll {
let! x = Gen.choose 1 100
let! y = Gen.elements [ "a"; "b"; "c"; "d" ]
return! x < 50 || y = "a"
}
```
You get output like this:
```
 *** Failed! Falsifiable (after 2 tests and 5 shrinks):
 50
 "b"
 val it : bool = false
```
@moodmosaic I think this is nice for scripts, and it works well in a Haskell setting, but I imagine there's a more idiomatic way to report test errors for things like xUnit that I'm not really familiar with. I would appreciate any guidance you have on that matter. I'm full time on Haskell these days, it's been a number of years since I was a …
> Bare bones module for checking properties

- Jack.Tests/App.config
- Jack.Tests/Jack.Tests.fsproj
- Jack.Tests/Library1.fs
- Jack.Tests/ShrinkTests.fs
- Jack.Tests/paket.references
- Jack/Shrink.fs
- paket.dependencies
- paket.lock
This pull request adds a test module for writing example-based tests, as well as property-based tests, for the functions in the `Shrink` module.
Adding the very first test required setting ['redirects: on' in Paket](https://fsprojects.github.io/Paket/dependencies-file.html#Redirects-option), as well as referencing FSharpx.Collections.
> Add an example-based test for Shrink.removes

- Jack/Gen.fs
- Jack/Jack.fsproj
- Jack/Numeric.fs
- Jack/Property.fs
- Jack/Random.fs
- Jack/Script.fsx
- Jack/Shrink.fs
I decided to diverge from some of the traditional names for things to try an make them fit better into an F# style.
Haskell QuickCheck -> F# Jack
`elements` -> `Gen.item`
`choose` -> `Gen.range`
`oneof` -> `Gen.choice`
`listOf` -> `Gen.list` / `Gen.array` / `Gen.seq`
@moodmosaic Would be interested to know what you think.
> Add combinators for shrinking, choice, numbers, strings, collections

- Jack/Gen.fs
- Jack/Property.fs
- Jack/Script.fsx
By implementing `Delay` and `Zero` on the `forAll` builder, it means that if statements work as expected:
```fs
Property.check <| forAll {
let! n = Gen.int
if n <> 0 then
return 1 / n = 1 / n
}
// +++ OK, passed 100 tests.
```
> Support for conditional generators and conditional properties

- Jack/Property.fs
- Jack/Script.fsx
I also renamed the `forAll` builder to `property` as I think it's more correct. I think this name is better, not completely sure.
/cc @moodmosaic
> Support for 'where' and 'counterexample' custom operations

- Jack.Tests/Jack.Tests.fsproj
- Jack.Tests/MinimalTests.fs
- Jack.Tests/paket.references
- Jack/Gen.fs
- Jack/Jack.fsproj
- Jack/Property.fs
- Jack/Random.fs
- Jack/Script.fsx
- Jack/Tree.fs
- Jack/paket.references
- paket.dependencies
- paket.lock
`Property.print`, and the lower level `Property.report`, are available for experimentation in scripts.
This PR has a number of changes:
- `Property.check` becomes `Property.report` and returns a rich data type instead of a `bool`
- `Property.print` gives more or less the same behaviour as the previous `Property.check` although it doesn't return a `bool`, maybe it should
- `Property.check` throws the new exceptions `GaveUpException` and `FailedException` where appropriate, this allows for better integration with test runners, as per issue #34 
- Added `MinimalTests.fs` to check that shrinking gives a minimal counterexample and to check that the test runner integration works well
- Added some more operations to the `property` builder, you can now loop over sequences, do arbitrary effects, …
> Property.check now throws exceptions for better test runner integration

- Jack/Script.fsx
similar to 8714eb0 ("Move Jack.Tests.MinimalTests.genExp at the bottom,", 2016-10-22) in #36.
> Move #nowarn "40" compiler directive at the bottom,

- README.md
A preview of how it looks like is shown [here](https://github.com/moodmosaic/dotnet-hedgehog/blob/topic/readme-nuget-semver/README.md#nuget).
> Add NuGet installation instructions and related SemVer notes to the README.md

- src/Hedgehog/Script.fsx
In c451bba0c0e8254cd52b69bfce01a61e8c75f2de, and #76, we changed the directory structure but I forgot to update the references in Script.fsx.
> Update references in Script.fsx

- README.md
- src/Hedgehog/Gen.fs
- src/Hedgehog/Hedgehog.fsproj
- src/Hedgehog/Random.fs
- src/Hedgehog/Range.fs
- src/Hedgehog/Script.fsx
- tests/Hedgehog.Tests/MinimalTests.fs
This pull request is part of a series of pull requests on bringing `Gen` in line with the Haskell version (#89).
> Modify Gen combinators so that they take a Range

- README.md
- TUTORIAL.md
- doc/tutorial.md
This resolves #69.
It basically
* adds a doc/tutorial.md which contains most of the stuff from the old README.md, updated to use the Range combinators
* ports README.md from Haskell version, with any features we don't currently support being removed for now
You can see a preview [here](https://github.com/moodmosaic/fsharp-hedgehog/blob/topic/readme/README.md).
> Add doc/tutorial, make smaller README

- src/Hedgehog/Gen.fs
- src/Hedgehog/Script.fsx
In line with https://github.com/hedgehogqa/haskell-hedgehog/pull/73/.
> Add ascii/latin1/unicode character generators

- src/Hedgehog/Gen.fs
- src/Hedgehog/Shrink.fs
- tests/Hedgehog.Tests/ShrinkTests.fs
Based on Hedgehog 0.2.2 `Shrink.hs` module's [towardsFloat](
https://github.com/hedgehogqa/haskell-hedgehog/blob/51ebefc972235d07f25a462b6edbfe3ce507ccbc/hedgehog/src/Hedgehog/Internal/Shrink.hs#L38-L62).
> Shrink floating binary point types similar to the Haskell version

- src/Hedgehog/Range.fs
- tests/Hedgehog.Tests/RangeTests.fs
Implementation + doctests are based on the [current (v3.0) Haskell version](https://github.com/hedgehogqa/haskell-hedgehog/blob/0.3/hedgehog/src/Hedgehog/Range.hs).
> Add Range exponential combinators

- src/Hedgehog/paket.template
This is per the official F# guidelines at
https://fsharp.github.io/2015/04/18/fsharp-core-notes.html#do-not-bundle-fsharpcore-with-a-library,
the gist of which is:
> Do not include a copy of FSharp.Core with your library or package. If
> you do, you will create havoc for users of your library.
>
> The decision about which FSharp.Core a library binds to is up to the
> application hosting of the library. The library and/or library package
> can place constraints on this, but it doesn’t decide it.
> Exclude FSharp.Core NuGet dependency

- CHANGELOG.md
- src/Hedgehog/AssemblyInfo.fs
- Exclude FSharp.Core NuGet dependency (#109)
- Render exceptions so they get added to the journal (#119)
> Release 0.4

- .gitignore
- build.fsx
- src/Hedgehog/Range.fs
- src/Hedgehog/Shrink.fs
- src/Hedgehog/Tree.fs
- tests/Hedgehog.Tests/RangeTests.fs
- tests/Hedgehog.Tests/ShrinkTests.fs
Addresses #117 by removing `doctests` in favor of F# Formatting (#118). Any `doctests` that don't exist already as example-based tests are added in to the *Hedgehog.Tests* project.
The XML documentation shouldn't be hard to read now on Visual Studio and other tools supporting F#:
/cc @jystic @ploeh
> IDE-readable API documentation

- CHANGELOG.md
- src/Hedgehog/AssemblyInfo.fs
- Add ToBigInt overload for System.Double (#136)
> Release 0.4.3

- CHANGELOG.md
- src/Hedgehog/AssemblyInfo.fs
- Make Journal store delayed strings, so they are computed on-demand (#147)
> Version 0.6.0

- src/Hedgehog/Gen.fs
- tests/Hedgehog.Tests/GenTests.fs
I solved the issue #158.
closes #158
> fix for returning noncharacters from Gen.unicode

- src/Hedgehog/Numeric.fs
- tests/Hedgehog.Tests/GenTests.fs
This commit addresses that generating uint32 and uint64 returns
out-of-range values. This problem occurs in numeric conversions.
> fix for generating out-of-range values,

- src/Hedgehog/Numeric.fs
- src/Hedgehog/Range.fs
- tests/Hedgehog.Tests/GenTests.fs
https://github.com/hedgehogqa/fsharp-hedgehog/issues/185
The problem looks to be that the clamp on exponential ranges is performed after the conversion to the target type, so if the value falls just outside the range then an exception is thrown before the clamp occurs.
This moves the clamp to before the conversion, but maybe a better fix would be to sort out the calculation that's going out of bounds in the first place.
> Proposed fix for issue #185

- src/Hedgehog/Shrink.fs
This is more efficient than https://github.com/hedgehogqa/fsharp-hedgehog/commit/27c19dfeed4929d6e62fe6df269797eedcc7e650 as it avoids `Math.Min` entirely. See also #170.
> Fix a bug in Shrink.removes where List.take k xs runs before checking k > n

- src/Hedgehog/paket.template
Hi,
as you already noticed we have some generated files from obj folder also packed in the nuget package into fable folder.
I do not think fable compiler needs this.
I just added to ignore all files from obj folder when generating nuget package.
Hope this is OK.
> exclude obj directories from nuget package

- Hedgehog.sln
This PR makes the `Hedgehog.Benchmarks` project the default startup project by listing it first in the `sln` file.
This change improves the development experience. When first cloning the repo or after deleting the `.vs` directory and then opening the `sln` file with Visual Studio, the default startup project will now be the `Hedgehog.Benchmarks` project. This is an improvement because the `Hedgehog` project was the previous default startup project, but it cannot be executed.  (The two test projects can be started/executed, but I do not believe that it is intended behavior to do so.)
> Make Hedgehog.Benchmarks the default startup project

- tests/Hedgehog.Tests/MinimalTests.fs
This PR is related to issue #201 about the possibility of a test failing in the `master` branch.
For me, that test fails, and it fails very "late" in its execution.  I eventually determined that it fails because the reference it obtains to `genExp` is its `default` value.  (After realizing that, I found it easier to debug the failing test after removing `[<Struct>]` from the definitions of `Gen<>` and `Random<>`.  Then the test failed significantly sooner in its execution.)
This PR adds a test to ensure that `genExp` is not its default value (when `Gen<>` and `Random<>` are still defined with `[<Struct>]`... this test will fail if `[<Struct>]` is removed from the definition of either of those types).  It also adds some tests to ensure that the `isDefaultGen` test is implemented correctly. …
> Add test to ensure that genExp is not its default value

- src/Hedgehog/Hedgehog.fsproj
Fixes #204
I tested creation of the NuGet package by executing the command...
```
dotnet pack src/Hedgehog/Hedgehog.fsproj
```
...and it produced a NuGet package that listed these dependencies.
I think this the correct behavior.
> Target .NET Standard 2.0

- src/Hedgehog/Hedgehog.fsproj
- tests/Hedgehog.CSharp.Tests/Hedgehog.CSharp.Tests.csproj
- tests/Hedgehog.Tests/GenTests.fs
- tests/Hedgehog.Tests/Hedgehog.Tests.fsproj
Fixes #199 
The test projects target .NET Framework 4.6.1 since since this is the lowest version that has the issue I described in https://github.com/hedgehogqa/fsharp-hedgehog/issues/199#issue-648491997.
The main project targets .NET Framework 4.5 because that was the lowest version that worked for me.  I tried targeting version 4.0.3, but I got an error message saying something about needing to install an SDK.  I didn't feel like trying any harder than that.  Someone else can create a new issue if they want to investigate Hedgehog targeting version 4.0.3 or lower.
In the penultimate commit, I have 11 failing tests.  All are because a `MissingMethodException` was thrown.  None of them have the same message as the one I experienced in https://github.com/elmish/Elmish.WPF/issues/237, but I …
> Also target net45

- CHANGELOG.md
- src/Hedgehog/Hedgehog.fsproj
Compared to the [previous release (0.8.3)](https://github.com/hedgehogqa/fsharp-hedgehog/pull/188/files), there two differences.
1. Only changed the `Verson` element in `Hedgehog.fsproj` instead of both `AssemblyVersion` and `FileVersion` because of the change in c90f5a280b69a1856488f8275cd4934e18890bfd.
2. No change in `paket.template` because it doesn't exist anymore (c.f. #207).
> Release 0.8.4

- doc/tutorial.md
In both of these examples, `Property.print` doesn't just print the value of `a`; it also prints the value of `b`.
> added missing output of Property.print in tutorial examples

- src/Hedgehog/Gen.fs
I added the same sentence that exists in the [Haskell documentation for the frequency generator](https://hackage.haskell.org/package/hedgehog-1.0.3/docs/Hedgehog-Gen.html#v:frequency).
> added shrink direction to the frequency generator documentation

- src/Hedgehog/Gen.fs
- src/Hedgehog/Tree.fs
- tests/Hedgehog.Tests/Hedgehog.Tests.fsproj
- tests/Hedgehog.Tests/TreeTests.fs
Resolves #227
(This PR was previously PR #228 with a different branch name)
This gets the job done. I am open to feedback to adhere to the standards of the project or the preferences of the maintainers.
Based on comment https://github.com/hedgehogqa/fsharp-hedgehog/issues/226#issuecomment-719817482 by @moodmosaic, I named these functions `render` (instead of `toString` like in PR #228).
After looking more closely at the Haskell code, the function that returns `string list` I named `renderLines`.  I also restricted these functions to only work for trees containing data of type `string`.
> Add Tree to string function

- src/Hedgehog/Gen.fs
> Fix the 'atLeast' function

- .github/workflows/dotnet-core.yml
- tests/Hedgehog.Benchmarks/Hedgehog.Benchmarks.fsproj
- tests/Hedgehog.CSharp.Tests/Hedgehog.CSharp.Tests.csproj
- tests/Hedgehog.Tests/Hedgehog.Tests.fsproj
This PR upgrades the CI build to use version 3.1.403 of the .NET SDK.  This is the most recently released version.  The CI build is currently using version 2.1.4.  Both the 2.1 series and the 3.1 series are long-term support (LTS) releases.
I have created this PR to resolve the FS0058 warnings, which are about possibly incorrect indentations.  The F# compiler in the newer SDK is satisfied with the current indentation.
Most practically, this PR will remove these warnings from the files view of a pull request in GitHub.  A beta feature of GitHub under the heading [Unchanged files with check annotations](https://github.com/hedgehogqa/fsharp-hedgehog/pull/233/files#diff-9b7fcde4f0a23cc861c6b1da4c00e8eaf668e9db5a0b07ae8ab2527e3a76373fR66:~:text=Unchanged%20files%20with%20check%20annotations) …
> Reduce noise from GitHub's unchanged files with check annotations feature

- src/Hedgehog/Tree.fs
- tests/Hedgehog.Tests/TreeTests.fs
@moodmosaic, I just realized that you introduced a bug when you changed the implementation of `Tree.renderList` in PR #229.
This PR contains two commits.  The first commit increases the cases covered by the tests by changing the trees in the tests from full binary trees to full ternary trees.  The second commit reverts the implementation of `Tree.renderList` to how [my commit](https://github.com/hedgehogqa/fsharp-hedgehog/pull/229/commits/20d328df67e3def0a0e48b3875085e33237b0aca) computed the output.
In the second commit, I tried to keep all of your copy edits.  I am just trying to get back to an implementation that passes the tests.  Feel free to change it however you want again (but this time, try to not add a bug ;) :P ).
> Fix Tree.render bug

- src/Hedgehog/Tree.fs
- tests/Hedgehog.Tests/TreeTests.fs
Removes additional space character in the render of a tree as discussed in https://github.com/hedgehogqa/fsharp-hedgehog/issues/227#issuecomment-726357568.
> removed additional space in tree render #227

- src/Hedgehog/Property.fs
- tests/Hedgehog.Tests/GenTests.fs
> Adding recheck method and seed reporting

- src/Hedgehog/Hedgehog.fsproj
How about generating a NuGet package as part of the build?
In general, it is useful to know if some change prevents the ability to create the NuGet package.  More specifically, this helps test unreleased code.  Of course it is possible to add a direct dependency on the project, but it is easier to obtain and share the NuGet package and depend on it after putting it in a local NuGet package source.  In particular, this change would make it easier to test PR #251.
> Generate NuGet package during build

- src/Hedgehog/Range.fs
- tests/Hedgehog.CSharp.Tests/NameTests.cs
Fixes https://github.com/hedgehogqa/fsharp-hedgehog/issues/254
Cf. https://github.com/hedgehogqa/fsharp-hedgehog/pull/219/files
> Making documentation appear for F# in Visual Studio.

- src/Hedgehog/Gen.fs
- tests/Hedgehog.Tests/GenTests.fs
This PR consists of these changes, each in a separate commit:
* Improve correctness of Gen.dateTime docs (`DateTime` is decidedly not an instant in time; `DateTimeOffset` is). This change was also done for consistency with the new functions added in later commits.
* Added `Gen.dateTimeOffset`. It's a "primitive" that is non-trivial to generate (care must be taken to avoid overflows due to adding offsets around the min/max values) and should be in fsharp-hedgehog
* Added ranged variants of `Gen.dateTime` and `Gen.dateTimeOffset`, allowing users to specify their own date ranges (I have myself come across the need to limit the date ranges due to complicated time zone stuff some country did a hundred years ago, which is not interesting to account for in my domain)
* Implemented `dateTime` and …
> Improve and extend DateTime/DateTimeOffset generation

- .github/workflows/master.yml
- .github/workflows/pull_request.yml
- README.md
Resolves #215
This PR adds the GitHub Action called [Publish NuGet](https://github.com/marketplace/actions/publish-nuget).  When executed, it publishes a NuGet package if the version (as specified in the `Version` element in the project file) has changed.
I found it because it is being used in `fsharp-hedgehog-experimental` [here](https://github.com/hedgehogqa/fsharp-hedgehog-experimental/blob/master/.github/workflows/dotnet-core.yml#L24-L29) (and with help from @dharmaturtle).
I didn't copy things exactly as they are in `fsharp-hedgehog-experimental`.  Instead, I made it very clear when the publish NuGet package code will execute: only when `master` changes.  If the files were left together, I was concerned that anyone could create pull request that changes the version and cause a NuGet …
> automated publishing of NuGet package

- src/Hedgehog/Linq/Property.fs
- src/Hedgehog/Property.fs
It would be easier for Hedgehog.Xunit to implement `[<Recheck(size, seed)>]` if `reportRecheck` existed. I threw in `reportBool` as a bonus.
https://github.com/hedgehogqa/fsharp-hedgehog/pull/266 should probably go first, which'll break this PR but I'll fix it once it's in.
> Added reportBool, reportRecheck, and reportRecheckBool

- src/Hedgehog/Hedgehog.fsproj
Fixes #278
A few issues:
- Files under the `obj` folder were being included, some auto-generated `AssemblyInfo.fs` file or something, and these made it all the way into the nuget package.
- The `PackagePath` ended in a `\` which caused a weird pathing issue in the nuget package as well.
> Fix fable include

- src/Hedgehog/Linq/Gen.fs
- src/Hedgehog/Linq/Property.fs
- src/Hedgehog/Linq/Range.fs
The purpose of this PR is to hide another F# detail from the LINQ interface, in this case the `unit` type. When used as a return type, `unit` becomes `void`, but when used as a type argument then it remains as `FSharp.Core.Unit`. To solve this I've introduced the `Property` type, that just conceals a `Property<unit>` (ie, this is _not_ an alias). Then from C#/VB a user would just see this simple type instead of `Property<FSharp.Core.Unit>`.
> Hide unit type from LINQ interface

- src/Hedgehog/AutoOpen.fs
- src/Hedgehog/Hedgehog.fsproj
- src/Hedgehog/Journal.fs
- src/Hedgehog/Linq/Property.fs
- src/Hedgehog/Outcome.fs
- src/Hedgehog/Property.fs
- src/Hedgehog/Report.fs
- src/Hedgehog/Script.fsx
- src/Hedgehog/Shrink.fs
- src/Hedgehog/Tuple.fs
- src/Hedgehog/Util.fs
Fixes #246.
Also, while I moved `Result<'a>` I opted to rename it to `Outcome<'a>`, therefor this also fixes #181.
> Split Property.fs across multiple files

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- tests/Hedgehog.Linq.Tests/Hedgehog.Linq.Tests.csproj
This PR addresses some issues/changes with the project, just a quick overview:
- Use a `docker-compose.yml` file to mount in a volume to cache vscode extensions.
- Switch to using the `.editorconfig` that was added in #273.
- Ionide version 5 switched to requiring .NET 5, which this project doesn't yet support. So I've pinned the last version that works with .NET Core 3.0.
- Also, there's an issue with these extensions working across language barriers, this part I can remove. I changed `Hedgehog.Linq.Tests.csproj` to reference the local path for `Hedgehog.dll` so that omnisharp can find it. This was more useful when I was writing the LINQ interface.
> Update remote dev files

- src/Hedgehog/Gen.fs
- src/Hedgehog/Hedgehog.fsproj
- src/Hedgehog/OptionTree.fs
This PR adds `OptionTree.traverse`.  It uses the same naming convention I have been arguing for in PR https://github.com/hedgehogqa/fsharp-hedgehog/pull/260#discussion_r551046128.
However, to hopefully avoid the same discussion here, I made that module internal.  That way, we can easily change the name (i.e. without a breaking change).
> Add OptionTree.traverse

- src/Hedgehog/Hedgehog.fsproj
- src/Hedgehog/ListGen.fs
- tests/Hedgehog.Tests/GenTests.fs
This PR adds `ListGen.traverse` and its specialization `sequence`.
> add ListGen.traverse

- src/Hedgehog/Gen.fs
- src/Hedgehog/GenTuple.fs
- src/Hedgehog/Hedgehog.fsproj
- src/Hedgehog/Linq/Gen.fs
- src/Hedgehog/Linq/Property.fs
- src/Hedgehog/ListGen.fs
- src/Hedgehog/Property.fs
- src/Hedgehog/Random.fs
- src/Hedgehog/Tuple.fs
- tests/Hedgehog.Tests/GenTests.fs
- tests/Hedgehog.Tests/MinimalTests.fs
Fixes #265.
The goal is to allow better data flow through the combinators, like:
```fsharp
Gen.alpha
|> Gen.tryWith (fun exn -> ...)
|> Gen.bind (fun ch -> ...)
|> Gen.map (fun ch -> ...)
```
> Rearrange parameters for better chaining.

- src/Hedgehog/Linq/Property.fs
- src/Hedgehog/Property.fs
- src/Hedgehog/Script.fsx
- tests/Hedgehog.Linq.Tests/LinqTests.cs
- tests/Hedgehog.Tests/ShrinkTests.fs
Sometimes I don't want Hedgehog to shrink. For example, if I'm writing an [integration test with a temporary database](https://jacobstanley.io/how-to-use-hedgehog-to-test-a-real-world-large-scale-stateful-app/), it takes several seconds to spin up a new DB. When I'm in the initial stages of RedGreenRefactor, there's a _lot_ of red. Often the first test will immediately fail, but it will incur ~30 shrinks because my datatypes aren't simple. Those shrinks become quite time-expensive for no real benefit.
This PR adds an `(maxShrinks : int<shrinks> option)` parameter to `takeSmallest` which controls how many times shrinking will occur. I also added `Property.check''` and friends. I'm not fond of the name... but I'm out of ideas.
> Added PropertyConfig

- doc/index.md
I have no idea how the new fsdocs/gh-pages work, so here are some markdown edits. Perhaps we should wait until a release is cut before merging them though?
I'd like to make more drastic changes, but I'll wait until the fsdocs/gh-pages start to gain structure.
Also, there are many references to the "gen expression" and "property expression". Is there a reason why we aren't calling them "computation expressions"?
Also also, should we [disable the wiki](https://docs.github.com/en/github/building-a-strong-community/disabling-wikis) since we're going in the gh-pages direction?
> Slightly improved docs

- src/Hedgehog/Numeric.fs
This is the first in a series of PRs I am planning to put up, to enforce a consistent style across the project. I believe these changes follow the style guide (more or less), I also took this opportunity to re-order the functions in a consistent order. The order is
- `unit`
- `bool`
- `char`
- `unsigned` types
- `signed` types
- `float` types
- `decimal`
The integer types all use the `u?int\d+` aliases (`uint8`, `int8`, etc).
Functions were also grouped to reduce the instances of `#if !FABLE_COMPILER` directives.
`ToBigInt`/`FromBigInt` functions use composition now, to eliminate lint warnings.
If the style in this PR is approved, I can move forward and do similar changes in the other files.
> Tidy up Numeric.fs

- tests/Hedgehog.Linq.Tests/LinqTests.cs
fixes #283
This addresses an issue we've had in CI, where the tests for `PropertyExtensions.Where` hit a discard limit and fail. If we generate the data such that the predicate in `PropertyExtensions.Where` always evaluates to true, we will no longer hit the discard limit randomly.
> Fix flaky tests

- tests/Hedgehog.Tests/GenTests.fs
- tests/Hedgehog.Tests/Program.fs
- tests/Hedgehog.Tests/RangeTests.fs
- tests/Hedgehog.Tests/SeedTests.fs
- tests/Hedgehog.Tests/ShrinkTests.fs
- tests/Hedgehog.Tests/TestDsl.fs
- tests/Hedgehog.Tests/TreeTests.fs
Some housekeeping I did while going through the new Fable test-suite. Feel free to discuss and/or reject any or or all of those:
* remove redundant space
* remove unused `open` directives
* `testCaseNoFable` renamed to `fableIgnore`
* where possible maximum line width at 80 characters
* where possible use `expected`/`actual` test terminology
/cc @adam-becker @TysonMN
> Housekeeping

- CHANGELOG.md
- src/Hedgehog/Hedgehog.fsproj
https://github.com/hedgehogqa/fsharp-hedgehog/compare/v0.9.0...0bbc3fda6b8da4ac39a28c6ea21e43c007e27250
fixes #280
/cc @adam-becker @TysonMN @dharmaturtle @ThisFunctionalTom @cmeeren
:tada:
> Release 0.10.0

- src/Hedgehog/Hedgehog.fsproj
Just a small fix for a broken link in nuget package.
> fix link to tutorial in nuget package

- src/Hedgehog/Hedgehog.fsproj
- src/Hedgehog/Seq.fs
- src/Hedgehog/Shrink.fs
> made Seq module internal and moved to own file

- src/Hedgehog/Linq/Property.fs
- src/Hedgehog/Linq/PropertyConfig.fs
Instead of making an overload that accepts a null `PropertyConfig` then converting that to a valid one, this PR creates separate overloads so this can be handled statically with overload resolution.
> Remove PropertyConfig.coalesce

- src/Hedgehog/Gen.fs
- src/Hedgehog/Seq.fs
- src/Hedgehog/Shrink.fs
- src/Hedgehog/Tree.fs
- tests/Hedgehog.Tests/ShrinkTests.fs
Fixes #224
This PR changes the implementation of `Gen.integral` so that the shrink tree corresponds to the choices that binary search would make.
This is a draft PR because more testing is needed.  I "manually" tested it with `0` for `destination` and `4` for `x`, and the resulting tree matches my expectation, which I showed in https://github.com/hedgehogqa/fsharp-hedgehog/issues/224#issuecomment-724177320.
I don't know how to create an automated test for this.  The main problem is that calling `Gen.integral` includes randomness from the call to `Random.integral`.  If I try to extract the `createTree` function to avoid that randomness, then I get these compile errors and warning.
```
error FS1114: The value 'Hedgehog.Gen.createTree' was marked inline but was not bound in the optimization …
```
> Improved integral shrink trees to match behavior of binary search

- src/Hedgehog/Hedgehog.fsproj
- src/Hedgehog/Property.fs
- src/Hedgehog/PropertyArgs.fs
- src/Hedgehog/Report.fs
This PR adds a structure to keep all the run args in a single place. This will allow us to more easily add support for #25.
> Add property args structure.

- README.md
- doc/index.md
- doc/property.md
- src/Hedgehog/Gen.fs
- src/Hedgehog/Linq/Gen.fs
- src/Hedgehog/Linq/Property.fs
- src/Hedgehog/Linq/PropertyConfig.fs
- src/Hedgehog/Property.fs
- src/Hedgehog/PropertyConfig.fs
- src/Hedgehog/Script.fsx
Fixes #226 the name for `Gen.printSample` would be awkward (`Gen.toStringSample`) if the convention were followed.
> Add render functions

- src/Hedgehog/Property.fs
- tests/Hedgehog.Tests/Hedgehog.Tests.fsproj
- tests/Hedgehog.Tests/Program.fs
- tests/Hedgehog.Tests/PropertyTests.fs
> Special processing for printing ResizeArray<_> in Property.forAll #323

- src/Hedgehog/Range.fs
> Rename the parameters of Range.exponentialFrom (and friends)

- src/Hedgehog/Gen.fs
- src/Hedgehog/Tree.fs
- tests/Hedgehog.Tests/GenTests.fs
- tests/Hedgehog.Tests/TreeTests.fs
Fixes #319
We had the same bug that Haskell had.  They fixed this bug in PR https://github.com/hedgehogqa/haskell-hedgehog/pull/406.  I tried to mimic their solution here.  I think I was successful.
CC @HuwCampbell
I did one thing differently related to their `shrink` function.  I think the input `n` of the lambda to `shrink` is put into the root of the shrink tree by `shrink`.  Instead, I avoided an off-by-one error by first paring the weights and then calling `takeWhile`.  Without pairing, the resulting sequence does not include the weight corresponding to the weight `k` in the base case of `pick`.
> Remove duplicates in frequency shrink tree

- .editorconfig
- src/Hedgehog/Hedgehog.fsproj
- src/Hedgehog/Linq/Property.fs
- src/Hedgehog/Linq/Report.fs
- src/Hedgehog/Property.fs
- tests/Hedgehog.Linq.Tests/LinqTests.cs
Fixes #317
I added tests corresponding to those given in #317 except that they pass when the behavior is correct and fail otherwise.  Then I fixed the issue by implementing `Property.select` via `Property.bind` and especially `Property.ofThrowing`, which maps a thrown exception to `Outcome<_>.Failure`.
> Implement Property.select via bind to avoid bug

- src/Hedgehog/Gen.fs
Just a quick PR to remove an extra call to `Gen.sized`. The function passed to it is essentially `always (array range g)`, eliminating the only reason to used `Gen.sized`.
> Remove extra sized call

- src/Hedgehog/Gen.fs
In anticipation of something like #268, I think we should implement the `mapN` variants with `apply` instead of `bind`. The parameters passed in aren't sequentially dependent so `bind` doesn't make sense, though it works.
There is also less closure capturing with this approach, for whatever that's worth.
> Implement `Gen.mapN` variants with `Gen.apply`

- src/Hedgehog/Property.fs
This is a change that I am splitting off of draft PR #336. I think it is ready to merge now.
I think this is a better name for this (private) function.
> improve function name takeSmallest to shrinkInput in Property

- src/Hedgehog/GenTuple.fs
- src/Hedgehog/Tuple.fs
This is a change that I am splitting off of draft PR #336. I think it is ready to merge now.
This PR changes the access scope of two top-level modules from private to internal.  I didn't know that top-level modules could be private.  It seems to me that private and internal mean the same thing for top-level modules.  However, Visual Studio displayed the functions as transparent as though they were unused and returned no search results for references.  Strangely though, it was possible to navigate from a reference to one of these definitions.  None of these problems exist after changing the scope to internal.
> change access scope for two top-level modules from private to internal

- src/Hedgehog/Hedgehog.fsproj
This is a change that I am splitting off of draft PR #336.  I think it is ready to merge now.
This PR allows the `Hedgehog.Tests` project to access types and functions in the `Hedgehog` project that have internal scope.  This is helpful because we can be more conservative about adding to the public API while still adding tests for this code.
> allow tests to access internal scope

- src/Hedgehog/Property.fs
- tests/Hedgehog.Tests/PropertyTests.fs
Fixes #327
I think this PR fixes the bug where an exception isn't caught when checking a `Property<_>` containing `counterexample`.  I got the idea for this fix by looking at `Property.forall`, which is the only other place that `Property.counterexample` is called.  In the last commit, I removed the exception handling code from `Property.forall` since it is now happening in `Property.bind`.
How does this compare to the code in Haskell Hedgehog?
@AlexeyRaga, does the branch in this PR give the behavior that you expect?
> Fix for counterexample crashing bug #327

- src/Hedgehog/Property.fs
- tests/Hedgehog.Tests/PropertyTests.fs
This PR is similar to PR #328, which fixed bug #327 by adding error handling to `Property.bind`.  Specifically, it adds essentially the same error handling to `Property.map`.  The first commit adds a failing test and the second commit makes that test pass.
This work is also adjacent to draft PR #336.  That draft currently has code similar (but weaker than due to its use of `Property.bind`) to error handling code in this PR.
> Add error handling to Property.map

- .gitignore
- tests/Hedgehog.Benchmarks/Hedgehog.Benchmarks.fsproj
- tests/Hedgehog.Benchmarks/Program.fs
Updated benchmark project to the latest `BenchmarkDotNet` version (`0.11.3` -> `0.13.1`). I also took the liberty to remove the explicit `FSharp.Core` reference, and I added another benchmark case for the `ForLoopTest`.
The `ForLoopTest` results show that we have some work to do there.. but that will be addressed in the future.
> Update benchmark project

- src/Hedgehog/Gen.fs
- src/Hedgehog/Random.fs
- tests/Hedgehog.Tests/GenTests.fs
> make Gen.{sampe, sampleTree} and Random.replicate lazy

- src/Hedgehog/Gen.fs
- src/Hedgehog/Random.fs
I removed the computation expression builder for `Random`. One function in `Gen` was using it, and that function has been rewritten to not need it.
> Remove 'Random.Builder'

- src/Hedgehog/Linq/Property.fs
This is (part of) the correct fix for #317.  I originally fixed that bug in PR #318 by implementing `Property.Select` via `Property.bind`.  However, I just (without realizing it until now) implemented the correct fix in PR #348.  Now this PR changes `Property.Select` to once again be implemented via `Property.map` as it should be.
> simplify fix for #317

- src/Hedgehog/Linq/Property.fs
- src/Hedgehog/Property.fs
I don't think `Property.ofThrowing` needs to exist.  Its purpose was to convert an exception into a property with a failed outcome.  That conversion how happens in both `Property.map` and `Property.bind`, so I can't think of any reason why this function needs to exist.
In the process of removing this, I improved/simplified a `Property.SelectMany` method by replacing a call to `bind` with a call to `map`.
> remove Property.ofThrowing

- tests/Hedgehog.Tests/TestDsl.fs
Here is a screenshot of the tooltip for `Expect.equal` that shows the branch in this PR has the arguments in the correct order.
> Fix order of arguments to Expect.equal

- .devcontainer/Dockerfile
- Hedgehog.sln
- src/Hedgehog/Seed.fs
- tests/Hedgehog.DieHarder/Hedgehog.DieHarder.fsproj
- tests/Hedgehog.DieHarder/Program.fs
- tests/Hedgehog.Tests/SeedTests.fs
Following a discussion in #360, I've made this branch and PR.
This PR covers a few things I noticed in `Seed.fs`:
- Naming of `goldenGamma` changed to match the F# naming guidelines.
- Magic numbers for `range` replaced with preexisting int64 min/max constants.
- Verbiage of some comments were updated, and a small doc comment for `Gamma` was added.
- The `split` function has been corrected to match the `SplitMix` paper, as well as Haskell Hedgehog.
- The `nextSeed` function has been inlined to the one call site it was referenced in, after other clean ups were applied.
/cc @moodmosaic, @TysonMN
> Fix a few things in our Seed implementation

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- tests/Hedgehog.Linq.Tests/Hedgehog.Linq.Tests.csproj
- tests/Hedgehog.Tests/Hedgehog.Tests.fsproj
Taken from #353. This removes the hard-coded UID/GID, fixes the startup command to also `dotnet restore`, and normalizes our test project files (`netcoreapp3.0` is going to be deprecated soon).
> Update dev container and project files.

- src/Hedgehog/Tree.fs
- tests/Hedgehog.Tests/TreeTests.fs
There are two ways in which the old and new children in `Tree.bind` can be concatenated.  As [discussed here](https://well-typed.com/blog/2019/05/integrated-shrinking/#:~:text=Although%20this%20version%20of%20join%20still%20satisfies%20the%20monad%20laws%2C%20it%20is%20strictly%20worse.), one of those ways is better than the other.
There is another tests that sort of covers this, but it is very indirect and sometimes passes (when the order is wrong).  That tests is 1greedy traversal with a predicate yields the perfect minimal shrink`.
This PR adds a specific and deterministic test to ensure that we are using the better order.
> Add test for concat order in Tree.bind

- tests/Hedgehog.Benchmarks/GenBenchmarks.fs
- tests/Hedgehog.Benchmarks/Hedgehog.Benchmarks.fsproj
- tests/Hedgehog.Benchmarks/Program.fs
This PR puts the examples from #135 into a proper benchmark, in support of #371.
> Add benchmarks for `Gen.sample`

- CHANGELOG.md
- src/Hedgehog/Property.fs
- tests/Hedgehog.Tests/PropertyTests.fs
> Fix bug preventing rendering of reports containing None

- .github/workflows/master.yml
- .github/workflows/pull_request.yml
- CHANGELOG.md
- src/Hedgehog/Property.fs
- tests/Hedgehog.Benchmarks/Hedgehog.Benchmarks.fsproj
- tests/Hedgehog.Benchmarks/Program.fs
- tests/Hedgehog.Linq.Tests/Hedgehog.Linq.Tests.csproj
- tests/Hedgehog.Tests/GenTests.fs
- tests/Hedgehog.Tests/Hedgehog.Tests.fsproj
- tests/Hedgehog.Tests/PropertyTests.fs
- tests/Hedgehog.Tests/ShrinkTests.fs
This PR is makes progress on issue #332.  This PR should be merged before PR #336 (which is still only a draft).  After this PR is merged, I will force push an update to the branch in that PR that includes a rebase on top of the branch in this PR.
The main point of this PR is to add `BindReturn` to the `Property` computational expression.  As [the corresponding RFC says](https://github.com/fsharp/fslang-design/blob/main/FSharp-5.0/FS-1063-support-letbang-andbang-for-applicative-functors.md#:~:text=nodes-,BindReturn%20-%20adds,Bind2Return,-%2C)
> - `BindReturn` - adds support and/or efficiency for `let! ... return`
That is preciously what we need to avoid testing non-shrunken inputs during rechecking.
One "controversial" thing this PR does is remove the `Return(bool)` method from the …
> Add BindReturn to Property CE

- CHANGELOG.md
- src/Hedgehog/Linq/Property.fs
- src/Hedgehog/Property.fs
- src/Hedgehog/PropertyArgs.fs
- src/Hedgehog/Report.fs
- tests/Hedgehog.Tests/Hedgehog.Tests.fsproj
- tests/Hedgehog.Tests/Program.fs
- tests/Hedgehog.Tests/ReportTests.fs
> Change recheck API to accept recheck data as string

- CHANGELOG.md
- src/Hedgehog/Property.fs
- src/Hedgehog/PropertyArgs.fs
- src/Hedgehog/Report.fs
This really isn't an improvement on its own, but this will simplify PR #336.
`reportWith'` currently populates `Outcome.Failure.Status` with the return value from a call to `shrinkInput`.  With the optimized rechecking in PR #336, no shrinking occurs when rechecking.  Instead, `Outcome.Failure.Status` is populated after following the shrink path with an instance of `Status.Failed` that doesn't need to provide recheck data.
> Add RecheckInfo to simplify recheck reporting

- CHANGELOG.md
- src/Hedgehog/Gen.fs
- src/Hedgehog/Tree.fs
- tests/Hedgehog.Tests/GenTests.fs
- tests/Hedgehog.Tests/TreeTests.fs
Resolves #397
...at least that is the plan.  Currently this is a draft PR.  The behavior is not correct yet.  There is a failing test.
> Applicative Gen.apply

- CHANGELOG.md
- src/Hedgehog/Property.fs
- tests/Hedgehog.Tests/PropertyTests.fs
This PR is stacked on top of PR #399, which is stacked on top of PR #398. Those PRs should be completed first.
> Fix Journal bug in Property.BindReturn

- CHANGELOG.md
- src/Hedgehog/Gen.fs
- src/Hedgehog/Property.fs
- tests/Hedgehog.Tests/GenTests.fs
- tests/Hedgehog.Tests/PropertyTests.fs
Resolves #268
...at least that is the plan. Currently this is a draft PR.  I don't yet know how to add support for `and!` to the `property` CE.
This PR is stacked on top of PR #401, which is stacked on top of #399, which is stacked on top of #401. Those PRs should be completed first.
> Applicative CE

- CHANGELOG.md
- src/Hedgehog/Property.fs
- tests/Hedgehog.Tests/PropertyTests.fs
> 408 fix recheck

- .github/workflows/master.yml
- .github/workflows/pull_request.yml
- CHANGELOG.md
- src/Hedgehog/Hedgehog.fsproj
- tests/Hedgehog.Benchmarks/Hedgehog.Benchmarks.fsproj
- tests/Hedgehog.Linq.Tests/Hedgehog.Linq.Tests.csproj
- tests/Hedgehog.Tests/Hedgehog.Tests.fsproj
Solves #411.
These two warnings remain:
```
NuGet.Build.Tasks.Pack.targets(221, 5): [NU5125] The 'licenseUrl' element will be deprecated. Consider using the 'license' element instead.
NuGet.Build.Tasks.Pack.targets(221, 5): [NU5048] The 'PackageIconUrl'/'iconUrl' element is deprecated. Consider using the 'PackageIcon'/'icon' element instead. Learn more at https://aka.ms/deprecateIconUrl
```
> Change .NET runtime targets to current recommendations

- README.md
- doc/index.md
The example properties are of type `Property<bool>`, and thus the correct type annotation should be used as well as the correct render function. As they are now in the documentation (prior to this edit), neither of these example properties compile.
> Fix introductory examples

- src/Hedgehog/Gen.fs
- tests/Hedgehog.Tests/GenTests.fs
> Add function Gen.timeSpan

- src/Hedgehog/Gen.fs
- tests/Hedgehog.Tests/GenTests.fs
> Add Gen.bigint

- doc/index.md
In the page https://hedgehogqa.github.io/fsharp-hedgehog/ the links in the table of content do not work, because of mismatches in the case (e.g. `getting-started` instead of `Getting-started`).
This PR fixes this.
I also noticed there was a duplicated link, which I removed.
> Anchor works in the website too

- tests/Hedgehog.Tests/Hedgehog.Tests.fsproj
Starting from version 0.15.*, the YoloDev.Expecto.TestSdkpackage targets .NET 8. Since the test project is using .NET 6, it fails to build with newer versions. To ensure compatibility and successful builds, the package version is specified to 0.14.3, which supports .NET 6.
> Specify the YoloDev.Expecto.TestSdk package version to 0.14.3
