hedgehogqa/fsharp-hedgehog

- Jack.Tests/AssemblyInfo.fs
- Jack.Tests/Jack.Tests.fsproj
- Jack.Tests/Library1.fs
- Jack.Tests/Script.fsx
- Jack.sln
@moodmosaic hope you don't mind
> Rename Jack.UnitTests -> Jack.Tests

- Jack/Gen.fs
- Jack/Random.fs
- Jack/Tree.fs
Too bad both 'return' and 'pure' are reserved words in F#, oh well
> I think Gen.constant and Tree.singleton are clearer names than result

- Jack/Script.fsx
because I think that's what most users look for when learning a new property-based testing tool.
> Add the standard "hello-world" property in script.fsx,

- Jack/Gen.fs
- Jack/Script.fsx
> Renamed Gen.suchThat -> Gen.filter, added Gen.tryFilter, Gen.some, Gen.option

- Jack.Tests/MinimalTests.fs
- Jack/Property.fs
as described on each commit message.
> Done some cleanup while looking at #35,

- Jack/Gen.fs
- Jack/Property.fs
- Jack/Random.fs
- Jack/Script.fsx
Unfortunately they still grow the stack each iteration, this might be fixable with a trampoline, but I was surprised how far we can get even with this implementation.
> Loops now work somewhat properly

- Jack.Tests/Jack.Tests.fsproj
- Jack.Tests/paket.references
- Jack/Jack.fsproj
- Jack/Numeric.fs
- Jack/Script.fsx
- Jack/paket.references
- paket.dependencies
- paket.lock
> Removed the dependency on FsControl,

- README.md
Yet another (boring) pull request :stuck_out_tongue_winking_eye: :open_mouth: :expressionless:
> Add some highlights to the readme

- README.md
based on the discussion at https://github.com/jystic/dotnet-jack/pull/54.
> Add some content to the readme,

- src/Hedgehog/Hedgehog.fsproj
- src/Hedgehog/Range.fs
- tests/Hedgehog.Tests/Hedgehog.Tests.fsproj
- tests/Hedgehog.Tests/RangeTests.fs
> Add Range type and combinators

- src/Hedgehog/Shrink.fs
These examples are ported from [Shrink.hs](https://github.com/hedgehogqa/haskell-hedgehog/blob/d3e2d75e1141e2f734f3a037cd635946726b9003/hedgehog/src/Hedgehog/Internal/Shrink.hs
), and run automatically when the project is build with
./build.sh
or manually with
./build.sh Doctest
> Add F# interactive examples to the Shrink module

- src/Hedgehog/Property.fs
- src/Hedgehog/Script.fsx
Resolves https://github.com/hedgehogqa/fsharp-hedgehog/issues/116.
> Render exceptions so they get added to the journal

- CHANGELOG.md
- src/Hedgehog/AssemblyInfo.fs
- XML-documentation improvements (#122)
- Typo fix in doc/tutorial.md (#121)
> Release 0.4.1

- src/Hedgehog/Property.fs
- src/Hedgehog/Script.fsx
Resolves https://github.com/hedgehogqa/fsharp-hedgehog/issues/124.
> Increase size in Discard case

- CHANGELOG.md
- src/Hedgehog/AssemblyInfo.fs
- Increase size in Discard case (#129)
> Release 0.4.2

- src/Hedgehog/Numeric.fs
- src/Hedgehog/Script.fsx
Resolves https://github.com/hedgehogqa/fsharp-hedgehog/issues/132
> Add ToBigInt overload for System.Double

- src/Hedgehog/Seed.fs
Resolves https://github.com/hedgehogqa/fsharp-hedgehog/issues/141, according to https://github.com/hedgehogqa/haskell-hedgehog/pull/124/.
> Correct mixGamma oddness check

- CHANGELOG.md
- src/Hedgehog/AssemblyInfo.fs
- Correct mixGamma oddness check (#142)
> Release 0.4.4

- CHANGELOG.md
- src/Hedgehog/AssemblyInfo.fs
- Support for LINQ queries (#113)
> Version 0.5.0

- src/Hedgehog/Seed.fs
* Use 64-bit unsigned integers as in https://github.com/hedgehogqa/haskell-hedgehog/pull/185
* Avoid weak gamma-γ values as in https://github.com/hedgehogqa/haskell-hedgehog/pull/198
/cc @jystic
> Sync F# version of Seed with Haskell

- CHANGELOG.md
- src/Hedgehog/Hedgehog.fsproj
- src/Hedgehog/paket.template
:confetti_ball: https://www.nuget.org/packages/Hedgehog/0.8.0
> Release 0.8

- CHANGELOG.md
- src/Hedgehog/Hedgehog.fsproj
- src/Hedgehog/paket.template
https://www.nuget.org/packages/Hedgehog/0.8.1
> Release 0.8.1

- src/Hedgehog/Gen.fs
- tests/Hedgehog.Tests/GenTests.fs
This PR addresses #127.  I have used  @cmeeren 's [approach](https://github.com/hedgehogqa/fsharp-hedgehog/issues/127#issuecomment-335388017). I want to add some unit tests, but it seems difficult or impossible. So I give up it.
Closes: #127
> Address generating datetime to include sub seconds

- CHANGELOG.md
- src/Hedgehog/Hedgehog.fsproj
- src/Hedgehog/paket.template
https://www.nuget.org/packages/Hedgehog/0.8.2
> Release 0.8.2

- README.md
ref.: #182 
c/c: @cmeeren, @jacobstanley
> Mention fsharp-hedgehog-experimental in README

- CHANGELOG.md
- src/Hedgehog/Hedgehog.fsproj
- src/Hedgehog/paket.template
https://www.nuget.org/packages/Hedgehog/0.8.3
> Release 0.8.3

- .gitignore
for Visual Studio Code and Rider(.NET IDE from Jetbrains)
> add gitignore patterns

- src/Hedgehog/Range.fs
https://github.com/hedgehogqa/fsharp-hedgehog/issues/156#issuecomment-702977269
> Explicitly instantiate static inline functions for C# callers

- src/Hedgehog/Range.fs
Copied the documentation from the Haskell codebase [here](https://github.com/hedgehogqa/haskell-hedgehog/blob/7030059c089b45429c9ed23f37971e1b5334dc2e/hedgehog/src/Hedgehog/Internal/Range.hs#L73-L81).
> copy paste Range documentation from Haskell

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- README.md
I got tired of juggling these files when making PRs, and I figure they might be of use to someone. These files allow the project to be opened in a Docker container with the [VS Code Remote Development][1] extension.
[1]: https://code.visualstudio.com/docs/remote/containers
> Add remote dev files

- src/Hedgehog/Gen.fs
> Add Gen.single and Gen.decimal

- CHANGELOG.md
- src/Hedgehog/Hedgehog.fsproj
https://github.com/hedgehogqa/fsharp-hedgehog/compare/v0.8.4...47289c355040de7ff343a31780b2e1201ad5ab9e
/cc
@adam-becker
@cmeeren
@dharmaturtle
@mausch
@TysonMN
> Release 0.9.0

- src/Hedgehog/Linq/Gen.fs
- src/Hedgehog/Linq/Property.fs
- src/Hedgehog/Outcome.fs
- src/Hedgehog/Property.fs
- src/Hedgehog/Range.fs
- src/Hedgehog/Report.fs
- src/Hedgehog/Seed.fs
- tests/Hedgehog.Linq.Tests/Hedgehog.Linq.Tests.csproj
- tests/Hedgehog.Linq.Tests/NameTests.cs
- tests/Hedgehog.Tests/ShrinkTests.fs
Feel free to reject any of those cleanups. /cc @adam-becker @TysonMN 
:rescue_worker_helmet:
> Housekeeping

- .editorconfig
- .gitignore
- Directory.Build.props
- build-docs.sh
- doc/index.md
- src/Hedgehog/Hedgehog.fsproj
This PR addresses some parameter issues that weren't straightened out during #277. I was able to use the files, along with these changes, to produce the current [documentation][documentation] site.
[documentation]: https://hedgehogqa.github.io/fsharp-hedgehog/
> Fix fsdocs parameters

- src/Hedgehog/Gen.fs
- src/Hedgehog/Tree.fs
> Rearrange Tree.bind parameters

- .editorconfig
> Sort .editorconfig properties

- src/Hedgehog/Hedgehog.fsproj
- src/Hedgehog/Linq/Property.fs
- src/Hedgehog/Linq/PropertyConfig.fs
- src/Hedgehog/Property.fs
- src/Hedgehog/PropertyConfig.fs
> Move property config to its own file.

- src/Hedgehog/Property.fs
Here are some refactors I made to simplify the code while working on issue #332.
> Refactors to simplify code mostly for takeSmallest

- CONTRIBUTING.md
To make getting started easier for newcomers, I've written some contributing guidelines. I don't want a very heavy process, but some process would make things clearer and prevent unnecessary work.
I think we could be a little clearer in the `Script.fsx` part.
We may want to start keeping track of benchmark output so we have a good baseline to compare new work to. Performance is going to be a metric I'm going to pay more attention to going forward.
> Add contributing guidelines.

- README.md
- tests/Hedgehog.Linq.Tests/LinqTests.cs
Fixes #331.
This includes some completely innocuous, tangentially related changes in the LINQ tests.
> Better C# example in README.md.

- README.md
> Fixed import namespace in cshrp sample

- CHANGELOG.md
- src/Hedgehog/Hedgehog.fsproj
https://github.com/hedgehogqa/fsharp-hedgehog/compare/v0.10.0...hedgehogqa:master
fixes #369
/cc @moodmosaic
> Release 0.11.0

- src/Hedgehog/Gen.fs
> Remove deprecated gens.

- CHANGELOG.md
- src/Hedgehog/ListGen.fs
- tests/Hedgehog.Tests/Hedgehog.Tests.fsproj
- tests/Hedgehog.Tests/ListGenTests.fs
- tests/Hedgehog.Tests/Program.fs
Resolves #339
This PR is stacked on top of PR #398.  That PR should be completed first.
> Applicative ListGen.traverse

- src/Hedgehog/Hedgehog.fsproj
In response to https://github.com/hedgehogqa/fsharp-hedgehog/issues/411#issuecomment-1195597503
> Targeted only netstandard2.0 in Hedgehog.fsproj

- src/Hedgehog/Linq/Property.fs
- src/Hedgehog/Property.fs
- src/Hedgehog/Report.fs
- tests/Hedgehog.Linq.Tests/LinqTests.cs
- tests/Hedgehog.Tests/ReportTests.fs
Resolves #432
Review happened in https://github.com/hedgehogqa/fsharp-hedgehog/issues/432#issuecomment-1629565074
> Speed up recheck

- src/Hedgehog/Property.fs
Resolves #418
Blocked by #433.  After that PR merges, this will only contain one commit, which is currently the last commit.
> Fix dead end message

- src/Hedgehog/Numeric.fs
- tests/Hedgehog.Tests/RangeTests.fs
> Fix decimal inline conversion

- src/Hedgehog/Numeric.fs
- tests/Hedgehog.Tests/RangeTests.fs
See issue here: https://github.com/fable-compiler/Fable/issues/3500
> add workaround for fable decimal bug
